### ISSUE TITLE
"\n" creates a new line, but also adds spaces.

### ISSUE THREAD

**Issue by FadiBunni** [modm-io/modm#142]
The "\n" or similar such as "modm::endl;" creates a new line, but also adds spaces. See picture below:
![capture](https://user-images.githubusercontent.com/14265546/50836155-c97d6980-1358-11e9-9344-bc5bf31abc10.PNG)

```c++
#include <blink/common/board.hpp>
#include <blink/common/config.hpp>
#include <modm/debug/logger.hpp>

using namespace modm::platform;

modm::IODeviceWrapper<Usart2, modm::IOBuffer::BlockIfFull> loggerDevice;
modm::log::Logger modm::log::info(loggerDevice);

// Set the log level
#undef	MODM_LOG_LEVEL
#define	MODM_LOG_LEVEL modm::log::INFO


int main(void) {
	Board::initialize();
	modm::IOStream stream(loggerDevice);	

	//MODM_LOG_INFO<< "hello" <<modm::endl;
	while(true){
		if(Board::Button::read()){
			
			loggerDevice.write("hello");
			loggerDevice.write("\n");
		 	for (int i = 0; i < 2; i++) {
				Board::LedGreen::toggle();
				modm::delayMilliseconds(250);

			}
		}
	}
	
	return 0;
}
```

**Comment by FadiBunni** [comment]
It needs to be "\r\n"

**Comment by salkinium** [comment]
`\n` is the line feed character, it only shifts the line one down. `\r` is the carriage return, it moves the cursor back to the beginning of the line.
We could make `modm::endl` configurable via a lbuild option to map it to `\r\n` (by default) or `\n` if so desired.

What are your opinions on this?
cc @rleh @dergraaf @chris-durand

**Comment by salkinium** [comment]
You can configure your terminal to map `\n` to `\r\n`, at least that‘s what I do with picocom.

**Comment by rleh** [comment]
## std::endl
```
template< class CharT, class Traits >
std::basic_ostream<CharT, traits>&endl(std::basic_ostream<CharT, Traits>& os );
```
Inserts a newline character into the output sequence os and flushes it as if by calling `os.put(os.widen('\n'))` followed by `os.flush()`.

This is an output-only I/O manipulator, it may be called with an expression such as `out << std::endl` for any `out` of type [std::basic_ostream](https://en.cppreference.com/w/cpp/io/basic_ostream). 

> From https://en.cppreference.com/w/cpp/io/manip/endl

**Comment by salkinium** [comment]
So we would keep the `\n` by default and optionally allow non-standard `\r\n` for convenience?

**Comment by rleh** [comment]
I would rather just add instructions on how to properly configure a serial terminal on the PC.

**Comment by rleh** [comment]
> ![capture](https://user-images.githubusercontent.com/14265546/50836155-c97d6980-1358-11e9-9344-bc5bf31abc10.PNG)

@FadiBunni Which serial terminal software did you use?

**Comment by salkinium** [comment]
Meh, looking through some other discussion on `std::endl` ([\[1\]](https://github.com/isocpp/CppCoreGuidelines/issues/357), [\[2\]](https://stackoverflow.com/questions/1651936/changing-stdendl-to-put-out-crlf-instead-of-lf), [\[3\]](http://chris-sharpe.blogspot.com/2016/02/why-you-shouldnt-use-stdendl.html)) I'd just leave our implementation just as it is.

Instead I want to focus on adding all or parts of [{fmt}](http://fmtlib.net/latest/index.html) to modm.

**Comment by salkinium** [comment]
For future reference, I let picocom remap my input like this:
```
picocom --imap lfcrlf -b 115200 /dev/tty.usbserialXYZ
```

**Comment by thestumbler** [comment]
I'm experimenting with `modm` and ran into this running my first example. In the last five minutes my opinion has flip flopped back and forth twice. I agree with what's been said above and the conclusion. A couple of things stick in my mind, however...

One of those discussions points out that standard C++ will tailor the `endl` behavior depending on what operating system you're running on, adopting the standard of the platform. These days that's basically either \n or \r\n, although long ago apparently Macs used \r. I don't know if `modm` swaps newline endings when running on Windows or not -- I haven't tried to tackle running it on Windows (yet), just focusing on Linux, MacOS, and WSL. Eventually I'll need to dig into Windows, because my client runs all Windows machines.

The problem comes up when you cross compile and the target doesn't match the build platform. In embedded systems, my area of interest for applying `modm`, this is true 99% of the time. And furthermore, these is no "standard platform" was of handling newlines in embedded applications, where you might be using ostream to send data for all kinds of different reasons -- an embedded file system, and interfaces whose format is beyond your control and has fixed newline requirements (NMEA for example).

I'm so new at `modm` I have no idea how difficult any such change would be if warranted. It does seem to me that this is something best left to the application, as noted above. There's just no reasonable choice you could make even if you wanted to, at least in the case of most embedded applications. Changing your terminal settings works great if you're using a terminal emulator, less so if you're using a real terminal or even a dumb dot-matrix printer for logging. 

For now, in my code, I'm just going to not use `endl` and use a macro or static const to define an application-wide NEWLINE variable. And for the record, I lean towards the Unix camp's line-feed-only as the newline character for almost everything. But when sending to a terminal, without something in the middle like `termcap`, you're on your own and have to consider these things.

And so far, I'm really liking this framework as it applies to embedded projects.

**Comment by salkinium** [comment]
Eh, I'm older now and more pragmatic. We can just make it configurable via lbuild. Then modm only needs to justify the default value, and can just comfortably… delegate all the issues with the host receiver settings to the developer, bwarharhar ;-P

> And so far, I'm really liking this framework as it applies to embedded projects.

Thank you!
