### ISSUE TITLE
Use C++17 language features

### ISSUE THREAD

**Issue by salkinium** [modm-io/modm#18]
We're already using C++14 by default, which requires at least GCC 5.
This is an issue for the official avr-gcc from Atmel which ships with Ubuntu in version 4.9.3.
Most other linux distributions, as well as [macOS via Homebrew](https://github.com/osx-cross/homebrew-avr) (Q: what about Windows?) compile their own avr-gcc from upstream, which is missing support for several AVR architectures and devices.
For the sake of moving forwards, we've accepted this caveat and are using a [self-compiled avr-gcc 7.3.0](https://github.com/salkinium/docker-avr-gcc-7/) for our CI.
ARM already ships arm-none-eabi-gcc for v7.2.0 since the 2017q4 release.

The [C++ standards support page for GCC](https://gcc.gnu.org/projects/cxx-status.html) shows that all language features of C++17 (except fixes to template argument deduction for class templates) are supported by GCC 7.
I would therefore like to enable C++17 as the default for modm to already make use of very useful new features such as `constexpr if`, enhancements to variadic templates, selection statements with initializers, constexpr lambdas and many more.

cc @dergraaf @strongly-typed @rleh @chris-durand @daniel-k @ekiwi @georgi-g @mhthies

**Comment by siy** [comment]
It was the thing which I was about to ask for.

**Comment by rleh** [comment]
## `arm-none-eabi-gcc`
* ARM toolchain: [GCC 7.1](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)
    * [PPA for Ubuntu](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa) :+1:
    * Download (precompiled) for Windows :+1:
    * Download (precompiled or source) for *Linux 64-bit* :+1:
* Ubuntu (since bionic): [GCC 6.3.1](https://packages.ubuntu.com/bionic/gcc-arm-none-eabi) :-1: (but PPA see above)
* Debian: [GCC 5.4.1](https://packages.debian.org/stretch/gcc-arm-none-eabi) :-1:
* Fedora: [GCC 7.1.0](https://apps.fedoraproject.org/packages/arm-none-eabi-gcc-cs) with CodeSourcery patches :+1:
* Arch Linux: [GCC 8.1.0](https://www.archlinux.org/packages/community/x86_64/arm-none-eabi-gcc/) :+1:
* macOS via Homebrew: [GCC 7.2.0](https://github.com/osx-cross/homebrew-arm) :+1:
* Docker Container for CI: [GCC 7.2.0](https://github.com/modm-io/docker-arm-none-eabi-gcc) :+1:

## `avr-gcc`
* [Official Atmel toolchain 3.6.1](http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/): [GCC 5.4](http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.6.1/avr8-gnu-toolchain-readme.pdf) :-1:
* Debian: [GCC 4.9.2](https://packages.debian.org/stretch/gcc-avr) based on Atmel toolchain 3.5.3 :-1:
* Ubuntu (since Artful): [GCC 5.4.0](https://packages.ubuntu.com/artful/gcc-avr) based on Atmel toolchain 3.6.0 :-1:
* Fedora: [GCC 7.2.0](https://apps.fedoraproject.org/packages/avr-gcc) :+1:
* Arch Linux: [GCC 8.1.0](https://www.archlinux.org/packages/community/x86_64/avr-gcc/) :+1:
* macOS via Homebrew: [GCC 7.2.0](https://github.com/osx-cross/homebrew-avr) :+1:
* Docker Container for CI: [GCC 7.3.0](https://github.com/salkinium/docker-avr-gcc-7) :+1:
* Arduino ships with [GCC 4.9.2](https://www.arduino.cc/en/Main/ReleaseNotes) :-1:
* Somebody built [GCC 8.1 for Windows](http://blog.zakkemble.co.uk/avr-gcc-builds/) in May 2017 :+1:

**Comment by salkinium** [comment]
If you use 32-bit Linux, well… meh.
I guess in the worst case you can always provide a Docker container for some precompiled avr-gcc.

I think this is happening.

**Comment by rleh** [comment]
> 32-bit Linux

Who uses 32-bit Linux today?

The Ubuntu PPA and Fedora include i386/i686 builds of avr-gcc and arm-none-eabi-gcc.

Oh, Raspberry Pi still has no official 64-bit software support :unamused: 
Raspbian has no avr-gcc and arm-none-eabi-gcc packages, but Fedora has ARMv7 and Aarch64 packages of avr-gcc and arm-none-eabi-gcc.

**Comment by salkinium** [comment]
> Oh, Raspberry Pi still has no official 64-bit software support 😒

Also missing x86 support 😒

**Comment by salkinium** [comment]
> I think this is happening.

It happened.

**Comment by daniel-k** [comment]
\o/
