### ISSUE TITLE
I2C broken (again)

### ISSUE THREAD

**Issue by strongly-typed** [modm-io/modm#45]
Discovery F4 [accelerometer example](https://github.com/modm-io/modm/blob/develop/examples/stm32f4_discovery/accelerometer/main.cpp) does not work when set `#define USE_I2C true`. It still works in c442b5ce1 in modm and [xpcc](https://github.com/roboterclubaachen/xpcc/releases/tag/2018q2).

Can we please have a QA Checklist, like [Screenly](https://www.forgett.com/checklist/1789089623)?

**Comment by salkinium** [comment]
I would assume some issue in [BitBang connect method](https://github.com/modm-io/modm/blob/develop/src/modm/platform/i2c/bitbang/bitbang_i2c_master_impl.hpp#L63), since the BitBang I2C code hasn't changed.

> QA Checklist

Checklists will work for processes, not unit testing.
We need to add more self-contained hardware unittests like I did for [testing the GPIO API](https://github.com/modm-io/modm/tree/develop/test/modm/platform/gpio).
Then the unittest execution can be put on a checklist.
