### ISSUE TITLE
STM32F469I-DISCO touch does not work on newer board revisions (B-03)

### ISSUE THREAD

**Issue by rleh** [modm-io/modm#818]
ST exchanged the touch screen controller [FT6206](https://modm.io/reference/module/modm-driver-ft6x06/) ([datasheet](https://cdn-shop.adafruit.com/datasheets/FT6x06+Datasheet_V0.1_Preliminary_20120723.pdf)) by FT6336 ([datasheet](https://focuslcds.com/content/FT6236.pdf)).

Touch controller on rev B-01:
![Touchcontroller_rev_B-01](https://user-images.githubusercontent.com/2820734/152552527-0bad4fb9-65ba-4e46-b4b4-03d4a085a6ec.jpg)
![image](https://user-images.githubusercontent.com/2820734/152553084-6dc1a430-0623-47c7-86cd-002e5ed17377.png)

Touch controller on rev B-03:
![Touchcontroller_rev_B-03](https://user-images.githubusercontent.com/2820734/152552534-2166bb2d-f357-40a8-9c42-03000ef7ba6d.jpg)
![image](https://user-images.githubusercontent.com/2820734/152553106-a0e05ad4-3d25-4cb8-8e44-c67e98dbb053.png)

---

The driver is basically the same, but the I²C address has changed from `0x2a` to `0x38`. Should get fixed in the STM32F469I-DISCO board support package / examples.
I'm not aware of any way to detect the board revision from software, maybe we could try to ping the touch screen controller during initialization and then use the I²C address that responded?
Otherwise we could duplicate the lbuild board module or add a revision option to the lbuild module?

cc @kikass13 @macslow

**Comment by kikass13** [comment]
> I'm not aware of any way to detect the board revision from software, maybe we could try to ping the touch screen controller during initialization and then use the I²C address that responded?

yeah, bus scan the shit out of that 7 bit adress space ! :D

**Comment by salkinium** [comment]
Each `I2cDevice` has a `setAddress()` function to change the address at runtime. You can `RF_CALL_BLOCKING(ping())` and then change the address inside the right `Board::initialize()` function?

**Comment by salkinium** [comment]
If that fails you could always add an option to the BSP module of course that would add the right driver dependency, but it won't be as elegant as adding the `/revN` to the target string.
Maybe something like `<extends>modm:disco-f469/revb03</extends>` would be really cool, I could probably hack that into lbuild, but it could also be achieved by having a second bsp module: `<extends>modm:disco-f469-b03</extends>`.
It would be cool though to always declare the revision by default (which is really part of the board identifier) and then get fixes later for free (just like with the `/revN` target string). Currently you're out of luck, because you *must* use `modm:disco-f469` since `modm:disco-f469-b03` doesn't exist, so lbuild could ignore the `/revb03` part if it doesn't find it.

**Comment by salkinium** [comment]
I'm basically just talking myself into implementing this in lbuild. I've already made up my mind, I just need to rationalize it… THE BLUEPILL/REDPILL CHOICE IS AN ILLUSION!1!!

**Comment by salkinium** [comment]
> You can `RF_CALL_BLOCKING(ping())` and then change the address inside the right `Board::initialize()` function?

I forgot that the touch sensor is optional and therefore not instantiated by default, therefore the application needs to set the address.
I've added proper config version support and added a `Board::ft6::TouchAddress` that changes depending on the config version that the application must set.
