### ISSUE TITLE
RP2040 modm::chrono::micro_clock::now() is imprecise when called from Core1

### ISSUE THREAD

**Issue by cocasema** [modm-io/modm#907]
When I was working on nrf24 code, I tried moving the rf logic to Core1, and got lots timeouts and delays. This initially got me thinking about some hw slowness due to locks etc, but luckily it narrowed down to `micro_clock` being very imprecise when called from Core1. While running on Core0, the delays between nrf24 write and interrupt ack would be  ~350us, and on Core1 I was getting 0 and ~1ms.

RP2040 provides [microsecond time via 64 bit counter](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf#page=537). 
And if I replace the code of `modm::chrono::micro_clock::now()` in `platform/clock/systick_timer.cpp` with reading the `timer_hw->timel*` registers, I get reliable time with a microsend resolution on both cores.

I can make a PR with the changes. Q: Should I `%if` the implementation based on the target and keep it in the same systick_timer.cpp
or should `modm::chrono::micro_clock::now()` be moved to some rp2040 related file for this case?

**Comment by salkinium** [comment]
It's a race-condition between the two cores that are accessing the [same `interrupt` variable](https://github.com/modm-io/modm/blob/develop/src/modm/platform/clock/systick/systick_timer.cpp.in#L22).
You could fix it for CM0 by making it an `bool interrupt[2]` array and using CPUID to index the right bool. The interrupt would set both true then.

You can still add the 64-bit counter as a separate module in the clock folder. The systick module should be optional (ie. only the BSP should pull it in), intentionally so that there can be alternate implentations. Not sure how FreeRTOS would then work on a dual-core systems with a single Systick though, probably only single core?

**Comment by cocasema** [comment]
Thanks!
