### ISSUE TITLE
Problem with SPI Mode 3 on STM32F469

### ISSUE THREAD

**Issue by hshose** [modm-io/modm#984]
I'm trying to use SPI in Mode 3 on STM32F469, like this:

<details>

<summary> 

Details (click to see complete `main.cpp`)

```cpp
Cs::reset();
RF_CALL_BLOCKING(SpiMaster::transfer(0xaa));
RF_CALL_BLOCKING(SpiMaster::transfer(nullptr, buffer.data(), 1));
Cs::set();
modm::delay(20us);
SpiMaster::setDataMode(SpiMaster::DataMode::Mode3);
modm::delay(20us);
Cs::reset();
RF_CALL_BLOCKING(SpiMaster::transfer(0xaa));
RF_CALL_BLOCKING(SpiMaster::transfer(nullptr, buffer.data(), 1));
Cs::set();
```

</summary>

```cpp
#include <modm/board.hpp>
#include <modm/processing.hpp>

using namespace Board;

using SpiMaster = modm::platform::SpiMaster2;

using Cs   = D9;
using Mosi = D11;
using Miso = D12;
using Sck  = D13;


int
main()
{
    Board::initialize();
    Cs::setOutput(modm::Gpio::High);

    SpiMaster::connect<Miso::Miso, Mosi::Mosi, Sck::Sck>();
    SpiMaster::initialize<Board::SystemClock, 351_kHz>();

    MODM_LOG_INFO       << "==========SPI Mode 3 The Fuck Test==========" << modm::endl;


    std::array<uint8_t,2> buffer;

    Cs::reset();
    RF_CALL_BLOCKING(SpiMaster::transfer(0xaa));
    RF_CALL_BLOCKING(SpiMaster::transfer(nullptr, buffer.data(), 1));
    Cs::set();

    modm::delay(20us);
    SpiMaster::setDataMode(SpiMaster::DataMode::Mode3);
    modm::delay(20us);

    Cs::reset();
    RF_CALL_BLOCKING(SpiMaster::transfer(0xaa));
    RF_CALL_BLOCKING(SpiMaster::transfer(nullptr, buffer.data(), 1));
    Cs::set();

    while (true)
    {
    
        Board::LedOrange::toggle();
    }

    return 0;
}
```

</details>

In the default (mode 0) everything works fine, however, after I change to mode 3, the CS goes high one clock cycle early and there are another 7 (wtf?) clock cycles.

Im a bit puzzled...

![image](https://user-images.githubusercontent.com/60779091/226772528-137b8621-bd64-4328-8688-b25a6a7e365f.png)

According to [RM0386](https://www.st.com/resource/en/reference_manual/rm0386-stm32f469xx-and-stm32f479xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), it looks like the `setDataMode` function sets the correct bits in the `SPI_CR1` register...

**Comment by rleh** [comment]
I can't reproduce the bug on Nucleo-F429ZI (using both `SpiMaster1` and `SpiMaster2`):

![image](https://user-images.githubusercontent.com/2820734/226948292-8b673f94-0cf7-4cf2-afc8-08e215f8b9bd.png)

[Code](https://github.com/modm-io/modm/commit/b31381da9e291c04bb01321aab79bfd102ab8f36)

**Comment by chris-durand** [comment]
I can reproduce it on a Nucleo F446ZE:
![SCR03](https://user-images.githubusercontent.com/25187160/226976256-4df0c32f-c421-4822-97b4-adaac55c54d5.PNG)

(The scope decoding function is set up for SPI mode 3. Thus, decoding the first two bytes fails although the data is fine).

The issue is that reconfiguring the SPI mode is not allowed while the peripheral is enabled. In the `initialize()` function it is [done correctly](https://github.com/modm-io/modm/blob/2c29b6780d9d5d56811e148c64e8727b79008ecf/src/modm/platform/spi/stm32/spi_hal_impl.hpp.in#L40).

When I'm doing
```
SPI2->CR1 &= ~SPI_CR1_SPE;
SpiMaster::setDataMode(SpiMaster::DataMode::Mode3);
SPI2->CR1 |= SPI_CR1_SPE;
```

everything works as it should:
![SCR04](https://user-images.githubusercontent.com/25187160/226978061-321ae823-e60f-45f7-ad5d-5c96c8c8fae1.PNG)

I haven't looked at a solution in detail, but probably the `setDataMode()` function should take care of disabling the peripheral while changing the setting.

**Comment by hshose** [comment]
The solution by @chris-durand works well. In addition, we had to add `__DSB()`.
This is what a complete lambda inside a configuration handler could look like:
```cpp
	this->attachConfigurationHandler([]() {
		SPI2->CR1 &= ~SPI_CR1_SPE;
		__DSB();
		SpiMaster::setDataMode(SpiMaster::DataMode::Mode3);
		SPI2->CR1 |= SPI_CR1_SPE;
		__DSB();
	});
```
